-- =====================================================
-- Smart Pharmacy Inventory & Expiry Management System
-- File: 03_insert_sample_data.sql
-- Description: Inserts sample data into all tables.
-- =====================================================
INSERT INTO categories (category_name, description)
VALUES
('Antibiotic', 'Medicines used to treat bacterial infections'),
('Painkiller', 'Medicines used to relieve pain'),
('Vitamin', 'Nutritional supplements'),
('Antifungal', 'Medicines used to treat fungal infections'),
('Antacid', 'Medicines used to reduce stomach acid');

SELECT * FROM categories;

INSERT INTO suppliers (
    supplier_name,
    contact_person,
    phone,
    email,
    city
)
VALUES
('Apollo Distributors', 'Ramesh Kumar', '9876543210', 'ramesh@apollodist.com', 'Hyderabad'),
('Sun Pharma Supply', 'Priya Sharma', '9876543211', 'priya@sunpharma.com', 'Mumbai'),
('Cipla Healthcare', 'Amit Verma', '9876543212', 'amit@cipla.com', 'Pune'),
('Dr. Reddy''s Distribution', 'Suresh Reddy', '9876543213', 'suresh@drreddys.com', 'Hyderabad'),
('Mankind Pharma Supply', 'Neha Gupta', '9876543214', 'neha@mankind.com', 'Delhi');

SELECT * FROM suppliers;


INSERT INTO medicines (
    medicine_name,
    category_id,
    unit_price,
    manufacturer
)
VALUES
('Amoxicillin 500mg', 1, 120.00, 'Cipla'),
('Azithromycin 250mg', 1, 180.00, 'Sun Pharma'),
('Paracetamol 500mg', 2, 25.00, 'Dolo'),
('Ibuprofen 400mg', 2, 45.00, 'Abbott'),
('Vitamin C 500mg', 3, 150.00, 'Himalaya'),
('Multivitamin Tablets', 3, 220.00, 'Revital'),
('Clotrimazole Cream', 4, 95.00, 'Glenmark'),
('Fluconazole 150mg', 4, 75.00, 'Cipla'),
('Pantoprazole 40mg', 5, 110.00, 'Alkem'),
('Gelusil Tablets', 5, 60.00, 'Pfizer');


SELECT * FROM medicines;

INSERT INTO inventory (
    medicine_id,
    quantity_in_stock,
    reorder_level
)
VALUES
(1, 150, 30),
(2, 80, 20),
(3, 500, 100),
(4, 120, 25),
(5, 200, 50),
(6, 90, 20),
(7, 40, 15),
(8, 60, 15),
(9, 110, 30),
(10, 70, 20);

SELECT * FROM inventory;

SELECT *
FROM inventory
WHERE quantity_in_stock <= reorder_level;


SELECT medicine_id, quantity_in_stock
FROM inventory
ORDER BY quantity_in_stock DESC;


INSERT INTO purchases (
    medicine_id,
    supplier_id,
    purchase_date,
    quantity,
    purchase_price
)
VALUES
(1, 3, '2026-06-01', 100, 100.00),
(2, 2, '2026-06-02', 80, 150.00),
(3, 1, '2026-06-03', 500, 18.00),
(4, 4, '2026-06-04', 120, 35.00),
(5, 5, '2026-06-05', 200, 120.00),
(6, 2, '2026-06-06', 100, 180.00),
(7, 3, '2026-06-07', 50, 70.00),
(8, 3, '2026-06-08', 75, 55.00),
(9, 4, '2026-06-09', 150, 90.00),
(10, 1, '2026-06-10', 100, 45.00);

SELECT * FROM purchases;

INSERT INTO sales (
    medicine_id,
    sale_date,
    quantity,
    selling_price
)
VALUES
(1, '2026-06-15', 20, 120.00),
(2, '2026-06-15', 15, 180.00),
(3, '2026-06-16', 100, 25.00),
(4, '2026-06-16', 25, 45.00),
(5, '2026-06-17', 30, 150.00),
(6, '2026-06-17', 20, 220.00),
(7, '2026-06-18', 10, 95.00),
(8, '2026-06-18', 12, 75.00),
(9, '2026-06-19', 18, 110.00),
(10, '2026-06-19', 22, 60.00);

SELECT * FROM sales;


-- Total revenue generated by each medicine
SELECT
    medicine_id,
    SUM(quantity * selling_price) AS total_revenue
FROM sales
GROUP BY medicine_id;


SELECT
    m.medicine_name,
    SUM(s.quantity) AS total_units_sold
FROM sales s
JOIN medicines m
    ON s.medicine_id = m.medicine_id
GROUP BY m.medicine_name;

INSERT INTO expiry_batches (
    medicine_id,
    batch_number,
    manufacturing_date,
    expiry_date,
    quantity
)
VALUES
(1, 'AMX2026001', '2026-01-15', '2028-01-14', 100),
(2, 'AZI2026001', '2026-02-10', '2028-02-09', 80),
(3, 'PAR2026001', '2026-03-05', '2028-03-04', 500),
(4, 'IBU2026001', '2026-01-20', '2028-01-19', 120),
(5, 'VIT2026001', '2026-04-01', '2028-03-31', 200),
(6, 'MVT2026001', '2026-04-15', '2028-04-14', 90),
(7, 'CLO2026001', '2026-05-01', '2028-04-30', 40),
(8, 'FLU2026001', '2026-05-10', '2028-05-09', 60),
(9, 'PAN2026001', '2026-06-01', '2028-05-31', 110),
(10, 'GEL2026001', '2026-06-05', '2028-06-04', 70);

SELECT * FROM expiry_batches;
