-- =====================================================
-- Smart Pharmacy Inventory & Expiry Management System
-- File: 05_database_objects.sql
-- Description: Database objects including Views,
-- Indexes, Stored Procedures and Triggers.
-- =====================================================

USE smart_pharmacy_inventory;
- "Show me all medicines with their category, stock quantity, and reorder level."

CREATE VIEW vw_inventory_status AS
SELECT 
    m.medicine_id,
    m.medicine_name,
    c.category_name,
    i.quantity_in_stock,
    i.reorder_level
   FROM medicines AS m
   JOIN categories AS c
       ON m.category_id = c.category_id
     JOIN inventory AS i
         ON m.medicine_id = i.medicine_id;
         
  -- Query the View
   SELECT *
    FROM vw_inventory_status;
    
    -- "Show me the total revenue generated by each medicine."
    
    CREATE VIEW vw_medicine_sales_summary AS
    SELECT 
    m.medicine_id,
    m.medicine_name,
    SUM(s.quantity) AS total_units_sold,
    SUM(s.quantity * s.selling_price) AS total_revenue
    FROM medicines AS m
    JOIN sales AS s
        ON m.medicine_id = s.medicine_id
      GROUP BY
      m.medicine_id,
      m.medicine_name;
      
      SELECT *
      FROM vw_medicine_sales_summary;
      
      
      CREATE VIEW vw_low_stock_medicines AS
    SELECT 
    m.medicine_name,
    c.category_name,
    i.quantity_in_stock,
    i.reorder_level
    FROM medicines AS m
    JOIN categories AS c
        ON m.category_id = c.category_id
        JOIN inventory AS i
		ON m.medicine_id = i.medicine_id
      WHERE i.quantity_in_stock<=i.reorder_level;  
      
      SELECT *
      FROM vw_low_stock_medicines;
      
      -- Create an Index
      CREATE INDEX idx_medicine_name
      ON medicines(medicine_name);
      
      -- Verify the Index
      SHOW INDEX 
      FROM medicines;
      
      EXPLAIN SELECT *
      FROM medicines
      WHERE medicine_name = 'Paracetamol 500mg';
      
      
      -- "Every day I need to see medicines that are below their reorder level."
      DELIMITER $$
      
      CREATE PROCEDURE GetLowStockMedicines()
      BEGIN
           SELECT
				m.medicine_name,
                c.category_name,
                i.quantity_in_stock,
                i.reorder_level
              FROM medicines AS m
              JOIN categories AS c
                   ON m.category_id = c.category_id
               JOIN inventory AS i
					ON m.medicine_id = i.medicine_id
                WHERE i.quantity_in_stock<= i.reorder_level;
              END$$
              
              DELIMITER ;
              
              CALL GetLowStockMedicines();
              
              -- When a sale is made, the pharmacy's inventory should automatically decrease. Instead of relying on someone to manually update the inventory, we can use a trigger.
              --  Create the Trigger
         DELIMITER $$
         
         
       CREATE TRIGGER trg_update_inventory_after_sale
       AFTER INSERT ON sales
       FOR EACH ROW
       BEGIN
            UPDATE inventory
            SET quantity_in_stock = quantity_in_stock - NEW.quantity
            WHERE medicine_id = NEW.medicine_id;
          END$$
          
          DELIMITER ;
          
          -- Test the Trigger
          SELECT 
				medicine_id,
                quantity_in_stock
		  FROM inventory
          WHERE medicine_id = 1;
          
          -- Now insert a new sale:
          INSERT INTO sales
          (
          medicine_id,
          sale_date,
          quantity,
          selling_price
          )
          VALUES
          (
          1,
          CURDATE(),
          5,
          120.00
          );
          
          -- Transactions (START TRANSACTION, COMMIT, ROLLBACK)
        -- Start a Transaction
        
       START TRANSACTION;   
       -- Check Current Stock
       SELECT 
            medicine_id,
            quantity_in_stock
         FROM inventory
         WHERE medicine_id =2;
         
         -- Update Stock
        UPDATE inventory
        SET quantity_in_stock = quantity_in_stock - 10
        WHERE medicine_id= 2;
        
        ROLLBACK;
        
        -- Start a Transaction
        
         START TRANSACTION;  
         
           -- Check Current Stock
       SELECT 
            medicine_id,
            quantity_in_stock
         FROM inventory
         WHERE medicine_id =2;
         
         -- Update Stock
        UPDATE inventory
        SET quantity_in_stock = quantity_in_stock - 5
        WHERE medicine_id= 2;
        
         SELECT 
            medicine_id,
            quantity_in_stock
         FROM inventory
         WHERE medicine_id =2;
        
        ROLLBACK;
        
         SELECT 
            medicine_id,
            quantity_in_stock
         FROM inventory
         WHERE medicine_id =2;
         
         
      --   Rank Medicines by Revenue (RANK())
      
      SELECT 
      m.medicine_name,
      SUM(s.quantity * s.selling_price) AS total_revenue,
      RANK() OVER (
			ORDER BY SUM(s.quantity * s.selling_price) DESC
		)AS revenue_rank
        FROM medicines AS m
        JOIN sales AS s
           ON m.medicine_id = s.medicine_id
         GROUP BY
         m.medicine_id,
         m.medicine_name;
            
            
            -- Sequential Numbering (ROW_NUMBER())
            
        SELECT 
            medicine_name,
            unit_price,
            ROW_NUMBER() OVER (
					ORDER BY unit_price DESC
                    ) AS row_num
                 FROM medicines; 
                 
	-- Dense Ranking (DENSE_RANK())
    
    SELECT 
        medicine_name,
        unit_price,
        DENSE_RANK() OVER (
             ORDER BY unit_price DESC
             ) ASdense_rank
           FROM medicines;  
           
-- Compare the Three Ranking Functions

SELECT 
medicine_name,
unit_price,
ROW_NUMBER() OVER (ORDER BY unit_price DESC) ASrow_number,
RANK() OVER(ORDER BY unit_price DESC) AS rank_number,
DENSE_RANK() OVER (ORDER BY unit_price DESC) AS dense_rank_number
FROM medicines;


-- Check for Duplicate Medicine Names

SELECT 
	medicine_name,
    COUNT(*) AS duplicate_count
  FROM medicines
  GROUP BY medicine_name
  HAVING COUNT(*)>1;
  
  -- Find Medicines with Invalid Prices
  
  SELECT 
      medicine_id,
      medicine_name,
      unit_price
    FROM medicines
    WHERE unit_price <=0;
       
       -- Find Negative Inventory
       
       SELECT 
          inventory_id,
          medicine_id,
          quantity_in_stock
        FROM inventory
        WHERE quantity_in_stock < 0;
        
        -- Expiry Date Before Manufacturing Date
SELECT
	batch_id,
    batch_number,
    manufacturing_date,
    expiry_date
   FROM expiry_batches
   WHERE expiry_date <= manufacturing_date;
   
   -- Orphan Purchase Records
   
   SELECT 
		p.purchase_id,
        p.medicine_id
     FROM purchases AS p
     LEFT JOIN medicines AS m
			ON p.medicine_id = m.medicine_id
     WHERE m.medicine_id IS NULL;       
     
     -- Orphan Sales Records
     
     SELECT 
       s.sale_id,
       s.medicine_id
    FROM sales AS s
    LEFT JOIN medicines AS m
			ON s.medicine_id = m.medicine_id
   WHERE m.medicine_id IS NULL;   
   
   -- Inventory Below Reorder Level
   
   SELECT 
        m.medicine_name,
        i.quantity_in_stock,
        i.reorder_level
   FROM inventory AS i
   JOIN medicines AS m
			ON i.medicine_id = m.medicine_id
        WHERE i.quantity_in_stock <= i.reorder_level;    
        
        
        -- Business Dashboard Queries
       
       -- Report 1: Top 5 Selling Medicines
       
       SELECT 
			m.medicine_name,
            SUM(s.quantity) AS total_units_sold,
            SUM(s.quantity * s.selling_price) AS tatal_revenue
            FROM medicines m
            JOIN sales s 
            ON m.medicine_id = s.medicine_id
            GROUP BY
				m.medicine_id,
				m.medicine_name
            ORDER BY total_units_sold DESC
            LIMIT 5;
        
        
        -- Report 2: Revenue by Category
        
        SELECT 
			c.category_name,
            SUM(s.quantity *s.selling_price) AS total_revenue
          FROM categories c 
          JOIN medicines m 
          ON c.category_id = m.category_id
          JOIN sales s 
          ON m.medicine_id = s.medicine_id
          GROUP BY
                c.category_id,
                c.category_name
           ORDER BY total_revenue DESC;     
          
          
          -- Report 3: Supplier Performance
          
          SELECT 
              sp.supplier_name,
              COUNT(p.purchase_id) AS total_orders,
              SUM(p.quantity) AS total_quantity
           FROM suppliers sp
           JOIN purchases p 
           ON sp.supplier_id = p.supplier_id
           GROUP BY 
				sp.supplier_id,
                sp.supplier_name
            ORDER BY total_quantity DESC;    
            
            -- Report 4: Current Inventory Status
            
            SELECT 
            m.medicine_name,
            i.quntity_in_stock,
            i.reorder_level,
            CASE 
				WHEN i.quantity_in_stock <= i.reorder_level
                THEN 'Reorder Required'
                ELSE 'Stock Available'
			END AS stock_status
        FROM inventory i 
        JOIN medicines m 
        ON i.medicine_id = m.medicine_id;
        
        -- Report 5: Medicines Expiring Within 180 Days
        
        SELECT
    m.medicine_name,
    e.batch_number,
    e.expiry_date
FROM expiry_batches e
JOIN medicines m
ON e.medicine_id = m.medicine_id
WHERE e.expiry_date <= CURDATE() + INTERVAL 180 DAY
ORDER BY e.expiry_date;

 -- Report 6: Monthly Sales Revenue
 
 SELECT
    YEAR(s.sale_date) AS sales_year,
    MONTH(s.sale_date) AS sales_month,
    SUM(s.quantity * s.selling_price) AS monthly_revenue
FROM sales s
GROUP BY
    YEAR(s.sale_date),
    MONTH(s.sale_date)
ORDER BY
    sales_year,
    sales_month;
    
    -- Report 7: Highest Revenue Medicine
    
    SELECT
    medicine_name,
    total_revenue
FROM
(
    SELECT
        m.medicine_name,
        SUM(s.quantity * s.selling_price) AS total_revenue
    FROM medicines m
    JOIN sales s
    ON m.medicine_id = s.medicine_id
    GROUP BY
        m.medicine_id,
        m.medicine_name
) revenue_summary
ORDER BY total_revenue DESC
LIMIT 1;
