- "Show me all medicines with their category, stock quantity, and reorder level."

CREATE VIEW vw_inventory_status AS
SELECT 
    m.medicine_id,
    m.medicine_name,
    c.category_name,
    i.quantity_in_stock,
    i.reorder_level
   FROM medicines AS m
   JOIN categories AS c
       ON m.category_id = c.category_id
     JOIN inventory AS i
         ON m.medicine_id = i.medicine_id;
         
  -- Query the View
   SELECT *
    FROM vw_inventory_status;
    
    -- "Show me the total revenue generated by each medicine."
    
    CREATE VIEW vw_medicine_sales_summary AS
    SELECT 
    m.medicine_id,
    m.medicine_name,
    SUM(s.quantity) AS total_units_sold,
    SUM(s.quantity * s.selling_price) AS total_revenue
    FROM medicines AS m
    JOIN sales AS s
        ON m.medicine_id = s.medicine_id
      GROUP BY
      m.medicine_id,
      m.medicine_name;
      
      SELECT *
      FROM vw_medicine_sales_summary;
      
      
      CREATE VIEW vw_low_stock_medicines AS
    SELECT 
    m.medicine_name,
    c.category_name,
    i.quantity_in_stock,
    i.reorder_level
    FROM medicines AS m
    JOIN categories AS c
        ON m.category_id = c.category_id
        JOIN inventory AS i
		ON m.medicine_id = i.medicine_id
      WHERE i.quantity_in_stock<=i.reorder_level;  
      
      SELECT *
      FROM vw_low_stock_medicines;
      
      -- Create an Index
      CREATE INDEX idx_medicine_name
      ON medicines(medicine_name);
      
      -- Verify the Index
      SHOW INDEX 
      FROM medicines;
      
      EXPLAIN SELECT *
      FROM medicines
      WHERE medicine_name = 'Paracetamol 500mg';
      
      
      -- "Every day I need to see medicines that are below their reorder level."
      DELIMITER $$
      
      CREATE PROCEDURE GetLowStockMedicines()
      BEGIN
           SELECT
				m.medicine_name,
                c.category_name,
                i.quantity_in_stock,
                i.reorder_level
              FROM medicines AS m
              JOIN categories AS c
                   ON m.category_id = c.category_id
               JOIN inventory AS i
					ON m.medicine_id = i.medicine_id
                WHERE i.quantity_in_stock<= i.reorder_level;
              END$$
              
              DELIMITER ;
              
              CALL GetLowStockMedicines();
              
              -- When a sale is made, the pharmacy's inventory should automatically decrease. Instead of relying on someone to manually update the inventory, we can use a trigger.
              --  Create the Trigger
         DELIMITER $$
         
         
       CREATE TRIGGER trg_update_inventory_after_sale
       AFTER INSERT ON sales
       FOR EACH ROW
       BEGIN
            UPDATE inventory
            SET quantity_in_stock = quantity_in_stock - NEW.quantity
            WHERE medicine_id = NEW.medicine_id;
          END$$
          
          DELIMITER ;
          
          -- Test the Trigger
          SELECT 
				medicine_id,
                quantity_in_stock
		  FROM inventory
          WHERE medicine_id = 1;
          
          -- Now insert a new sale:
          INSERT INTO sales
          (
          medicine_id,
          sale_date,
          quantity,
          selling_price
          )
          VALUES
          (
          1,
          CURDATE(),
          5,
          120.00
          );
          
          
